### ISSUE TITLE
написати у файлі що ми вивчили

### ISSUE THREAD

**Issue by InvokerSoloMid** [Klop414/hell-oh1.2#8]

**Comment by Klop414** [comment]
я написав

**Comment by ivanfreiuk** [comment]
Я доклав багато зусиль до вирішення цеї проблеми. =)

**Comment by Klop414** [comment]
Яцкiв Андрiй:
виконавши цю лабораторну роботу я навчився користуватися github: 
-Створювати та редагувати репозиторii
-Створювати вiтки змiн, пiдтвердження iх в основнiй вiтцi
-Створювати спiльнi проекти, обговорення
-Додавати мiтки та коментарi
-Додавати спiвавторiв
-Спiльно вирiшувати задачы в командi

**Comment by Klop414** [comment]
написано
